version: '3.3'
services:
    db:
        image: $DB_IMAGE:$DB_VERSION
        container_name: db
        restart: unless-stopped
        ports:
            - "5434:5432"
        environment:
            - POSTGRES_USER=$DB_USER
            - POSTGRES_PASSWORD=$DB_PASSWORD
            - POSTGRES_DB=postgres
        volumes:
            - database:$DB_CONTAINER_PATH
        networks:
            - odoo-network
    odoo:
        image: $ODOO_IMAGE:$ODOO_VERSION
        container_name: odoo
        restart: unless-stopped
        depends_on:
            - db
        links:
            - db
        ports:
            - "8069:8069"
        volumes:
            - $CONF_LOCAL_PATH:$CONF_CONTAINER_PATH
            - $EXTRA_ADDONS_LOCAL_PATH:$EXTRA_ADDONS_CONTAINER_PATH
            - filestore:$ODOO_FILESTORE_CONTAINER_PATH
        command: odoo 
        networks:
           - odoo-network
        environment:
            - ADMIN_PASS=$ODOO_ADMIN_PASS
            - DB_PORT_5432_TCP_ADDR=db
            - DB_PORT_5432_TCP_PORT=5432
            - DB_ENV_POSTGRES_USER=$DB_USER
            - DB_ENV_POSTGRES_PASSWORD=$DB_PASSWORD
            - DB_ENV_POSTGRES_DB=postgres
            
networks:
     odoo-network:
       driver: bridge
volumes:
     database:
     filestore:
