version: '3.3'
services:
    db-develop:
        image: $DB_IMAGE:$DB_VERSION
        container_name: db-develop
        restart: unless-stopped
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_USER=$DB_USER
            - POSTGRES_PASSWORD=$DB_PASSWORD
            - POSTGRES_DB=postgres
        volumes:
            - database:$DB_CONTAINER_PATH
        networks:
            - develop-network
    odoo-develop:
        image: $ODOO_IMAGE:$ODOO_VERSION
        container_name: odoo-develop
        restart: unless-stopped
        depends_on:
            - db-develop
        links:
            - db-develop
        ports:
            - "8047:8069"
        volumes:
            - $CONF_LOCAL_PATH:$CONF_CONTAINER_PATH
            - $EXTRA_ADDONS_LOCAL_PATH:$EXTRA_ADDONS_CONTAINER_PATH
            - filestore:$ODOO_FILESTORE_CONTAINER_PATH
        networks:
           - develop-network
        command: odoo -i base
        environment:
            - DB_PORT_5432_TCP_ADDR=db-develop
            - DB_PORT_5432_TCP_PORT=5432
            - DB_ENV_POSTGRES_USER=$DB_USER
            - DB_ENV_POSTGRES_PASSWORD=$DB_PASSWORD
            - DB_ENV_POSTGRES_DB=postgres
            - ADMIN_PASS=$ODOO_ADMIN_PASS
    pgadmin4-develop:
        image: $PGADMIN_IMAGE:$PGADMIN_VERSION
        container_name: pgadmin4-develop
        environment:
            - PGADMIN_DEFAULT_EMAIL=$PGADMIN_MAIL
            - PGADMIN_DEFAULT_PASSWORD=$PGADMIN_PASSWORD
        ports:
            - "5555:80"
        depends_on:
            - db-develop
        links:
            - db-develop
        networks:
            - develop-network
        restart: unless-stopped
    wdb:
        image: kozea/wdb
        container_name: wdb
        ports:
            - "1984:1984"
        restart: unless-stopped    
networks:
     develop-network:
       driver: bridge
volumes:
     database:
     filestore:
