#!/bin/bash

ODOO_PATH="./odoo"

# Source .env to get variables
if [ -f ./.env ]; then
    source ./.env
fi

# Generate odoo.conf

 ( echo "[options]" ; \
	echo "\n #Reference: https://gist.github.com/Guidoom/d5db0a76ce669b139271a528a8a2a27f" ; \
        echo addons_path = /mnt/extra-addons ;  \
        echo data_dir = /var/lib/odoo ; \
        echo admin_passwd = $ODOO_ADMIN_PASS ) >> $ODOO_PATH/19/conf/odoo.conf
